"""area names

Revision ID: 9d086d8a30a5
Revises: 5fdb9ef478fb
Create Date: 2025-04-21 19:57:53.731329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d086d8a30a5'
down_revision: Union[str, None] = '5fdb9ef478fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('name', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE areas SET name = 'Default Name'")
    op.alter_column('areas', 'name', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('areas', 'name')
    # ### end Alembic commands ###
