"""proper souls

Revision ID: 00014265fde1
Revises: 9dfe06b6531e
Create Date: 2025-04-06 21:37:19.162106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00014265fde1'
down_revision: Union[str, None] = '9dfe06b6531e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('character_souls', sa.Column('aura', sa.Integer(), nullable=False))
    op.drop_column('character_souls', 'name')
    op.alter_column('characters', 'soul_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('characters_puppeting_id_fkey', 'characters', type_='foreignkey')
    op.drop_constraint('characters_soul_id_fkey', 'characters', type_='foreignkey')
    op.create_foreign_key(None, 'characters', 'character_souls', ['soul_id'], ['id'], ondelete='SET NULL')
    op.drop_column('characters', 'puppeting_id')
    op.alter_column('game_objects', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('game_objects_container_id_fkey', 'game_objects', type_='foreignkey')
    op.drop_constraint('fk_game_objects_puppeted_by_id', 'game_objects', type_='foreignkey')
    op.create_foreign_key(None, 'game_objects', 'game_objects', ['container_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'game_objects', 'character_souls', ['puppeted_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_objects', type_='foreignkey')
    op.drop_constraint(None, 'game_objects', type_='foreignkey')
    op.create_foreign_key('fk_game_objects_puppeted_by_id', 'game_objects', 'characters', ['puppeted_by_id'], ['id'])
    op.create_foreign_key('game_objects_container_id_fkey', 'game_objects', 'game_objects', ['container_id'], ['id'])
    op.alter_column('game_objects', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('characters', sa.Column('puppeting_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.create_foreign_key('characters_soul_id_fkey', 'characters', 'character_souls', ['soul_id'], ['id'])
    op.create_foreign_key('characters_puppeting_id_fkey', 'characters', 'game_objects', ['puppeting_id'], ['id'])
    op.alter_column('characters', 'soul_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('character_souls', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('character_souls', 'aura')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
