"""permission level at accounts

Revision ID: 5fdb9ef478fb
Revises: 76d235b00f72
Create Date: 2025-04-21 12:16:23.005128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fdb9ef478fb'
down_revision: Union[str, None] = '76d235b00f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add the column as nullable
    op.add_column('accounts', sa.Column('permission_level', sa.Integer(), nullable=True))

    # Step 2: Set a default value for existing rows (e.g., 0)
    op.execute("UPDATE accounts SET permission_level = 0")

    # Step 3: Alter the column to be non-nullable
    op.alter_column('accounts', 'permission_level', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'permission_level')
    # ### end Alembic commands ###
