"""test autogenerate

Revision ID: 1c05414a2c4d
Revises: c370a0abafd9
Create Date: 2025-03-29 23:44:52.901212

"""
import geoalchemy2
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c05414a2c4d'
down_revision: Union[str, None] = 'c370a0abafd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINTZ', srid=3857, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_objects_location', 'game_objects', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_objects_location', table_name='game_objects', postgresql_using='gist')
    op.drop_table('game_objects')
    # ### end Alembic commands ###
