"""first correction 1

Revision ID: 9dfe06b6531e
Revises: d25fe8822de1
Create Date: 2025-04-05 21:18:50.664703

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9dfe06b6531e"
down_revision: Union[str, None] = "d25fe8822de1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("characters", sa.Column("soul_id", sa.Integer(), nullable=False))
    op.drop_constraint("characters_account_id_fkey", "characters", type_="foreignkey")
    op.create_foreign_key(None, "characters", "character_souls", ["soul_id"], ["id"])
    op.drop_column("characters", "account_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characters",
        sa.Column("account_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "characters", type_="foreignkey")
    op.create_foreign_key(
        "characters_account_id_fkey", "characters", "accounts", ["account_id"], ["id"]
    )
    op.drop_column("characters", "soul_id")
    # ### end Alembic commands ###
