"""nd to 3d in index name

Revision ID: 4c1925db9e4e
Revises: 8dc4f18c4087
Create Date: 2026-05-10 08:31:06.540517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1925db9e4e'
down_revision: Union[str, None] = '8dc4f18c4087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_game_objects_location_nd'), table_name='game_objects', postgresql_ops={'location': 'gist_geometry_ops_nd'}, postgresql_using='gist')
    op.create_index('idx_game_objects_location_3d', 'game_objects', ['location'], unique=False, postgresql_using='gist', postgresql_ops={'location': 'gist_geometry_ops_nd'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_game_objects_location_3d', table_name='game_objects', postgresql_using='gist', postgresql_ops={'location': 'gist_geometry_ops_nd'})
    op.create_index(op.f('idx_game_objects_location_nd'), 'game_objects', ['location'], unique=False, postgresql_ops={'location': 'gist_geometry_ops_nd'}, postgresql_using='gist')
    # ### end Alembic commands ###
