"""use n-d gist op class on game_objects.location

Revision ID: 8dc4f18c4087
Revises: 8864f8da12b4
Create Date: 2026-05-09 19:40:25.484851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc4f18c4087'
down_revision: Union[str, None] = '8864f8da12b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_game_objects_location'), table_name='game_objects', postgresql_using='gist')
    op.create_index('idx_game_objects_location_nd', 'game_objects', ['location'], unique=False, postgresql_using='gist', postgresql_ops={'location': 'gist_geometry_ops_nd'})
    op.drop_index(op.f('idx_terrain_location'), table_name='terrain', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_terrain_location'), 'terrain', ['location'], unique=False, postgresql_using='gist')
    op.drop_index('idx_game_objects_location_nd', table_name='game_objects', postgresql_using='gist', postgresql_ops={'location': 'gist_geometry_ops_nd'})
    op.create_index(op.f('idx_game_objects_location'), 'game_objects', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###
