"""container to holder and stored to holds

Revision ID: f1b6c6664590
Revises: 4c1925db9e4e
Create Date: 2026-05-12 09:26:18.377483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b6c6664590'
down_revision: Union[str, None] = '4c1925db9e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_objects', sa.Column('holder_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_game_objects_container_id'), table_name='game_objects')
    op.create_index('ix_game_objects_holder_id', 'game_objects', ['holder_id'], unique=False)
    op.drop_constraint(op.f('game_objects_container_id_fkey'), 'game_objects', type_='foreignkey')
    op.create_foreign_key(None, 'game_objects', 'game_objects', ['holder_id'], ['id'], ondelete='SET NULL')
    op.drop_column('game_objects', 'container_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_objects', sa.Column('container_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'game_objects', type_='foreignkey')
    op.create_foreign_key(op.f('game_objects_container_id_fkey'), 'game_objects', 'game_objects', ['container_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_game_objects_holder_id', table_name='game_objects')
    op.create_index(op.f('ix_game_objects_container_id'), 'game_objects', ['container_id'], unique=False)
    op.drop_column('game_objects', 'holder_id')
    # ### end Alembic commands ###
