"""changing name to username in account

Revision ID: 8864f8da12b4
Revises: 3d1d4e292bfc
Create Date: 2026-05-09 18:42:53.149301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8864f8da12b4'
down_revision: Union[str, None] = '3d1d4e292bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("accounts", "name", new_column_name="username")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("accounts", "username", new_column_name="name")

    # ### end Alembic commands ###
